In [1]:
import pandas as pd
import os
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

pd.set_option("mode.copy_on_write", True)
results = {}

In [2]:
# Replace this with the path to your downloads folder
downloads_folder = (
    "/Users/Sam/Documents/Duke/Spring 2024/IDS 705/Final Project/uds-2024-pangolin/data"
)

# Initialize an empty list to hold dataframes
dfs = []

# Iterate over each year and read the corresponding CSV file
for year in range(2017, 2024):
    file_path = os.path.join(
        downloads_folder, f"{year}_LoL_esports_match_data_from_OraclesElixir.csv"
    )
    df = pd.read_csv(file_path)
    dfs.append(df)

# Concatenate all dataframes into one
df = pd.concat(dfs, ignore_index=True)

df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,TREU/1001490056,complete,http://matchhistory.euw.leagueoflegends.com/en...,EU CS,2017,Spring,0,2017-01-10 15:44:06,1.0,6.24,...,118.0,798.0,612.0,5.0,1.0,0.0,0.0,0.0,0.0,1.0
1,TREU/1001490056,complete,http://matchhistory.euw.leagueoflegends.com/en...,EU CS,2017,Spring,0,2017-01-10 15:44:06,1.0,6.24,...,100.0,533.0,96.0,-4.0,1.0,1.0,0.0,0.0,0.0,0.0
2,TREU/1001490056,complete,http://matchhistory.euw.leagueoflegends.com/en...,EU CS,2017,Spring,0,2017-01-10 15:44:06,1.0,6.24,...,131.0,1116.0,1227.0,18.0,1.0,1.0,0.0,0.0,0.0,2.0
3,TREU/1001490056,complete,http://matchhistory.euw.leagueoflegends.com/en...,EU CS,2017,Spring,0,2017-01-10 15:44:06,1.0,6.24,...,148.0,171.0,150.0,-1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,TREU/1001490056,complete,http://matchhistory.euw.leagueoflegends.com/en...,EU CS,2017,Spring,0,2017-01-10 15:44:06,1.0,6.24,...,1.0,246.0,83.0,6.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789679,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4.0,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789680,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4.0,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789681,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4.0,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789682,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4.0,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789683,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4.0,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Calculate the career stats for each unique champion
champ_career_stats = (
    df.groupby("champion")
    .agg(
        {
            "result": "mean",  # avg win rate
            "kills": "mean",
            "deaths": "mean",
            "assists": "mean",
            "teamkills": "mean",
            "teamdeaths": "mean",
            "firstbloodkill": "mean",
            "firstbloodassist": "mean",
            "firstbloodvictim": "mean",
            "team kpm": "mean",
            "ckpm": "mean",
            "damagetochampions": "mean",
            "dpm": "mean",
            "damageshare": "mean",
            "damagetakenperminute": "mean",
            "damagemitigatedperminute": "mean",
            "wardsplaced": "mean",
            "wpm": "mean",
            "wardskilled": "mean",
            "wcpm": "mean",
            "controlwardsbought": "mean",
            "totalgold": "mean",
            "earnedgold": "mean",
            "earned gpm": "mean",
            "earnedgoldshare": "mean",
            "goldspent": "mean",
            "total cs": "mean",
            "minionkills": "mean",
            "monsterkillsownjungle": "mean",
            "monsterkillsenemyjungle": "mean",
            "cspm": "mean",
            "goldat10": "mean",
            "xpat10": "mean",
            "csat10": "mean",
            "goldat15": "mean",
            "xpat15": "mean",
            "csat15": "mean",
        }
    )
    .reset_index()
)

champ_career_stats.set_index("champion", inplace=True)

champ_career_stats

,result,kills,deaths,assists,teamkills,teamdeaths,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,...,minionkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,goldat15,xpat15,csat15
champion,,,,,,,,,,,,,,,,,,,,,
Aatrox,0.510479,2.905565,2.742713,4.566249,14.032763,13.537099,0.081189,0.080860,0.128582,0.448515,...,226.507423,12.961454,4.045100,7.854453,3241.475496,4551.964811,75.907614,5217.964414,7241.766385,122.883129
Ahri,0.513365,3.598867,2.224996,6.459904,14.835015,13.904054,0.097414,0.113426,0.097100,0.473894,...,255.769612,7.006258,1.864831,8.328439,3404.014393,4655.741139,84.438883,5455.148443,7464.931042,136.456498
Akali,0.510768,4.532468,2.736479,4.238369,15.219793,14.104882,0.097959,0.060401,0.082117,0.478592,...,238.198051,7.147165,1.796134,7.736900,3304.707558,4632.751187,79.534684,5274.970245,7337.970062,127.618474
Akshan,0.524000,4.036000,3.020000,4.464000,15.304000,15.272000,0.132000,0.133621,0.112069,0.490104,...,237.184000,9.869565,3.173913,7.988502,3373.758621,4509.073276,78.228448,5559.586207,7249.262931,126.793103
Alistar,0.506278,0.751137,3.302122,8.801689,13.684889,13.624486,0.044585,0.207149,0.122130,0.435639,...,41.973208,0.067597,0.042400,1.323209,2199.513530,2526.976787,13.863083,3381.885427,3840.413357,22.196003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zeri,0.509332,4.681355,2.209736,5.132192,13.955936,13.538965,0.109122,0.080468,0.083811,0.446162,...,282.763517,20.127094,3.661084,9.690634,3453.880850,3273.531280,84.291547,5666.055396,5569.820439,135.778176
Ziggs,0.480351,3.046232,2.456773,5.929727,14.125751,15.485437,0.058715,0.107383,0.083118,0.435770,...,268.358299,13.096073,2.079944,8.578373,3353.396489,3759.919463,81.213216,5519.371384,6192.016529,131.014463
Zilean,0.485364,1.344665,2.076487,8.263456,13.535411,13.479698,0.052034,0.107570,0.108566,0.419105,...,138.326723,6.234860,0.970458,4.344359,2678.438247,3636.810757,42.082669,4192.618526,5810.472112,68.914343
Zoe,0.515921,3.340699,2.033235,5.306943,13.092570,12.701757,0.114196,0.111979,0.059989,0.410323,...,241.077920,13.885917,2.048190,7.930400,3438.632070,4658.951057,85.796991,5468.089333,7376.295048,136.377143
Zyra,0.478898,1.207580,3.286822,6.995693,13.629630,14.134367,0.040552,0.147279,0.130203,0.383681,...,31.536670,0.299290,0.484014,0.882310,2092.411953,2630.832444,3.842049,3349.740662,3982.822839,8.248666

In [10]:
# Filter out only the rows with complete data
team_records = df[df["datacompleteness"] == "complete"]

# Filter out only the rows for team records (not individual player records)
team_records = df[df["participantid"] <= 10]


# Function to fill in the picks
def fill_picks(group):
    picks = group["champion"].tolist()  # Get list of champions for the team
    for i, pick in enumerate(picks, start=1):
        group[f"pick{i}"] = pick
    return group


# Group by gameid and teamname, then apply the function
team_records = team_records.groupby(["gameid", "teamname"]).apply(fill_picks)

In [11]:
team_records.reset_index(drop=True, inplace=True)
team_records.drop(
    columns=[
        "gameid",
        "datacompleteness",
        "url",
        "league",
        "split",
        "playoffs",
        "date",
        "participantid",
        "side",
        "playername",
        "playerid",
        "teamname",
        "teamid",
        "pick6",
        "pick7",
        "pick8",
        "pick9",
        "pick10",
    ],
    inplace=True,
)

In [12]:
team_records.drop(
    columns=[
        "firsttothreetowers",
        "mountains",
        "towers",
        "firsttower",
        "firstbaron",
        "firstdragon",
        "dragons",
        "opp_dragons",
        "elementaldrakes",
        "opp_elementaldrakes",
        "infernals",
        "clouds",
        "firstmidtower",
        "oceans",
        "chemtechs",
        "hextechs",
        "dragons (type unknown)",
        "elders",
        "opp_elders",
        "firstherald",
        "heralds",
        "opp_heralds",
        "opp_void_grubs",
        "opp_towers",
        "turretplates",
    ],
    inplace=True,
)

In [13]:
team_records.drop(
    columns=[
        "void_grubs",
        "gspd",
        "opp_turretplates",
        "opp_barons",
        "barons",
        "monsterkillsenemyjungle",
        "monsterkillsenemyjungle",
        "opp_inhibitors",
        "inhibitors",
    ],
    inplace=True,
)

In [16]:
team_records_final = team_records.dropna()
team_records_final

,year,game,patch,position,champion,ban1,ban2,ban3,ban4,ban5,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
33000,2018,1.0,8.11,top,Aatrox,Graves,Taliyah,Irelia,Soraka,Nunu & Willump,...,129.0,250.0,1297.0,25.0,0.0,0.0,0.0,1.0,1.0,0.0
33001,2018,1.0,8.11,jng,Camille,Graves,Taliyah,Irelia,Soraka,Nunu & Willump,...,139.0,-88.0,-585.0,-43.0,1.0,2.0,2.0,0.0,2.0,2.0
33002,2018,1.0,8.11,mid,Lulu,Graves,Taliyah,Irelia,Soraka,Nunu & Willump,...,52.0,2757.0,2413.0,90.0,2.0,1.0,0.0,0.0,2.0,1.0
33003,2018,1.0,8.11,bot,Kai'Sa,Graves,Taliyah,Irelia,Soraka,Nunu & Willump,...,131.0,344.0,212.0,24.0,0.0,0.0,0.0,0.0,1.0,0.0
33004,2018,1.0,8.11,sup,Alistar,Graves,Taliyah,Irelia,Soraka,Nunu & Willump,...,22.0,-408.0,-110.0,3.0,0.0,1.0,1.0,2.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657870,2017,2.0,7.21,top,Shen,Camille,Kalista,Ornn,Orianna,Syndra,...,125.0,134.0,139.0,-13.0,2.0,0.0,0.0,0.0,0.0,1.0
657871,2017,2.0,7.21,jng,Gragas,Camille,Kalista,Ornn,Orianna,Syndra,...,49.0,135.0,347.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0
657872,2017,2.0,7.21,mid,Azir,Camille,Kalista,Ornn,Orianna,Syndra,...,139.0,-68.0,33.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0
657873,2017,2.0,7.21,bot,Varus,Camille,Kalista,Ornn,Orianna,Syndra,...,126.0,345.0,312.0,13.0,0.0,2.0,0.0,0.0,0.0,1.0
657874,2017,2.0,7.21,sup,Rakan,Camille,Kalista,Ornn,Orianna,Syndra,...,19.0,75.0,668.0,-16.0,0.0,2.0,0.0,0.0,0.0,1.0

In [19]:
team_records_final = team_records_final.join(
    champ_career_stats, on="champion", how="left", rsuffix="_champ"
)

In [23]:
team_records_final.reset_index(drop=True, inplace=True)
team_records_final.dropna(inplace=True)

In [39]:
# Concatenate all pick columns and opp_pick columns into two separate series
team_picks = pd.concat([team_records_final[f"pick{i}"] for i in range(1, 6)])
# opp_picks = pd.concat([team_records_final[f"opp_pick{i}"] for i in range(1, 6)])

# One-hot encode the concatenated series
team_picks_encoded = pd.get_dummies(team_picks, prefix="TeamPick", drop_first=True)
# opp_picks_encoded = pd.get_dummies(opp_picks, prefix="OppPick", drop_first=True)

# Group by the index (gameid) and sum the one-hot encoded columns
team_picks_encoded = team_picks_encoded.groupby(team_picks_encoded.index).sum()
# opp_picks_encoded = opp_picks_encoded.groupby(opp_picks_encoded.index).sum()

# Join the one-hot encoded columns with the team_records dataframe
edit_df = team_records.join(team_picks_encoded)

In [40]:
# Drop NA values
edit_df.dropna(inplace=True)

# Save the final dataframe to a CSV file
edit_df.to_csv("edit_df.csv", index=False)